
export const dummyProjects = [
  {
    id: "1",
    name: "Mobile App v2 Launch",
    code: "MAP",
    description: "Rebuild the mobile experience with a new design system and offline mode.",
    progress: 72,
    status: "On track",
    statusColor: "text-emerald-600 bg-emerald-500/10 border-emerald-500/20",
    memberCount: 6,
    dueDate: "Aug 14",
    iconColor: "bg-violet-500",
  },
  {
    id: "2",
    name: "Marketing Website Redesign",
    code: "WEB",
    description: "Ship the new marketing site with case studies and pricing calculator.",
    progress: 45,
    status: "At risk",
    statusColor: "text-orange-600 bg-orange-500/10 border-orange-500/20",
    memberCount: 4,
    dueDate: "Aug 22",
    iconColor: "bg-blue-500",
  },
  {
    id: "3",
    name: "Q3 Growth Experiments",
    code: "GRW",
    description: "Run 12 growth experiments across onboarding and activation.",
    progress: 88,
    status: "On track",
    statusColor: "text-emerald-600 bg-emerald-500/10 border-emerald-500/20",
    memberCount: 3,
    dueDate: "Sep 01",
    iconColor: "bg-pink-500",
  },
  {
    id: "4",
    name: "Design System 2.0,",
    code: "DS2",
    description: "Rebuild tokens, components and documentation on the new foundation.",
    progress: 30,
    status: "On track",
    statusColor: "text-emerald-600 bg-emerald-500/10 border-emerald-500/20",
    memberCount: 5,
    dueDate: "Sep 18",
    iconColor: "bg-indigo-500",
  },
  {
    id: "5",
    name: "Customer Portal",
    code: "PRT",
    description: "Self-serve portal for billing, seats and invoices.",
    progress: 100,
    status: "Completed",
    statusColor: "text-blue-600 bg-blue-500/10 border-blue-500/20",
    memberCount: 4,
    dueDate: "Jul 30",
    iconColor: "bg-teal-500",
  },
  {
    id: "6",
    name: "AI Assistant Beta",
    code: "AIB",
    description: "Ship the private beta of the AI planning assistant.",
    progress: 12,
    status: "Paused",
    statusColor: "text-slate-600 bg-slate-500/10 border-slate-500/20",
    memberCount: 3,
    dueDate: "Oct 04",
    iconColor: "bg-orange-500",
  },
];