export const API_ENDPOINTS = {
    AUTH: {
        REGISTER: '/auth/register',
        LOGIN: '/auth/login',
        LOGOUT: '/auth/logout',
        SESSION_CONTEXT: '/auth/session/context',
        SESSION_RECONCILE: '/auth/session/reconcile',
    },
    ORGANIZATION: {
        CREATE: '/organization',
        CURRENT: '/organization',
        UPDATE: '/organization',
        ALL: '/organization/all',
        SWITCH: '/organization/switch',
    },
    PROJECT: {
        CREATE: '/project',
        ALL: '/project',
        BY_ID: (id: string) => `/project/${id}`,
        UPDATE: (id: string) => `/project/${id}`,
        MEMBERS_ADD: (id: string) => `/project/${id}/members`,
        MEMBER_REMOVE: (id: string, userId: string) => `/project/${id}/members/${userId}`,
    },
    USER: {
        ALL: '/user/all',
        ME: '/user',
        CHANGE_PASSWORD: '/user/password',
    },
    ROLE: {
        ALL: '/role',
        ASSIGN: '/role/assign',
        REMOVE_MEMBER: '/role/member',
    },
    INVITATION: {
        SEND: '/invitation/send',
        ALL: '/invitation',
        VERIFY: (token: string) => `/invitation/verify/${token}`,
        ACCEPT: '/invitation/accept',
        REVOKE: (id: string) => `/invitation/${id}`,
        RESEND: (id: string) => `/invitation/resend/${id}`,
        DECLINE: '/invitation/decline',
        ACCEPT_FOR_USER: (id: string) => `/invitation/accept/${id}`,
        DECLINE_FOR_USER: (id: string) => `/invitation/decline/${id}`,
        MY_PENDING: '/invitation/my-pending',
    },
    DASHBOARD: {
        PRODUCTIVITY: '/dashboard/productivity',
        STATS: '/dashboard/stats',
    },
} as const
